#!/usr/bin/env bash
set -euo pipefail
run_dir="${1:?run dir required}"
test -s "$run_dir/train.log"
test -s "$run_dir/metadata.env"
test -s "$run_dir/layers.json"
test -s "$run_dir/profile.jsonl"
test -s "$run_dir/weights/manifest.json"
test -s "$run_dir/weights/weights.f32.bin"
test -s "$run_dir/weights/input_weight_hxk.fp16"
test -s "$run_dir/weights/input_bias.fp16"
test -s "$run_dir/weights/hidden_weight_hxk.fp16"
test -s "$run_dir/weights/hidden_bias.fp16"
test -s "$run_dir/weights/residual0_fc1_weight_hxk.fp16"
test -s "$run_dir/weights/residual0_fc1_bias.fp16"
test -s "$run_dir/weights/residual0_fc2_weight_hxk.fp16"
test -s "$run_dir/weights/residual0_fc2_bias.fp16"
test -s "$run_dir/weights/output_weight_hxk.fp16"
test -s "$run_dir/weights/output_bias.fp16"
test -s "$run_dir/checkpoint/manifest.json"
test -s "$run_dir/checkpoint/state.f32.bin"
grep -q '"format": "stream1_weights"' "$run_dir/weights/manifest.json"
grep -q '"dtype": "fp16"' "$run_dir/weights/manifest.json"
grep -q '"num_classes": 128' "$run_dir/weights/manifest.json"
grep -q '"hd1": 8' "$run_dir/weights/manifest.json"
grep -q '"hd2": 8' "$run_dir/weights/manifest.json"
grep -q '"original_hd1": 5' "$run_dir/weights/manifest.json"
grep -q '"original_hd2": 3' "$run_dir/weights/manifest.json"
grep -q '"nrd": 1' "$run_dir/weights/manifest.json"
grep -q '"format": "mgt_train_checkpoint"' "$run_dir/checkpoint/manifest.json"
grep -q '"sections": \["weights", "adam_m", "adam_v"\]' "$run_dir/checkpoint/manifest.json"
grep -q 'OUTPUT_DIM=1' "$run_dir/metadata.env"
grep -q 'HD1=5' "$run_dir/metadata.env"
grep -q 'HD2=3' "$run_dir/metadata.env"
grep -q 'NCCL_ENABLED=' "$run_dir/metadata.env"
grep -q 'RESUME_CHECKPOINT=' "$run_dir/metadata.env"
grep -q '"milliseconds":' "$run_dir/profile.jsonl"
grep -q '"memory_bytes":' "$run_dir/profile.jsonl"
