#include "mgt_cuda/bf16_batch_norm_epilogue.cuh"
#include <limits>
namespace mgt_cuda { namespace {
template<class Xhat> __device__ float LoadXhat(const Xhat*x,std::uint64_t q){return static_cast<float>(x[q]);}
template<> __device__ float LoadXhat<float>(const float*x,std::uint64_t q){return x[q];}
template<class Xhat> __device__ void StoreXhat(Xhat*x,std::uint64_t q,float v){x[q]=Xhat(v);}
template<> __device__ void StoreXhat<float>(float*x,std::uint64_t q,float v){x[q]=v;}
template<class Xhat> __global__ void Forward(const float*x,const float*mean,const float*inv,const float*gamma,const float*beta,const __nv_bfloat16*res,unsigned active,unsigned cap,unsigned logical,unsigned physical,Xhat*xhat,__nv_bfloat16*y,unsigned*mask){unsigned row=blockIdx.x,word=blockIdx.y,col=word*32+threadIdx.x;bool stored=row<cap&&col<physical,valid=stored&&row<active&&col<logical;std::uint64_t q=(std::uint64_t)row*physical+col;float z=0;if(valid){float n=(x[q]-mean[col])*inv[col];StoreXhat(xhat,q,n);z=n*gamma[col]+beta[col]+(res?__bfloat162float(res[q]):0.0f);}else if(stored)StoreXhat(xhat,q,0.0f);bool on=valid&&z>0.0f;if(stored)y[q]=__float2bfloat16_rn(on?z:0.0f);unsigned bits=__ballot_sync(0xffffffffU,on);if(threadIdx.x==0)mask[(std::uint64_t)row*((physical+31)/32)+word]=bits;}
template<class Xhat> __global__ void Backward(const float*up,const unsigned*mask,const Xhat*xhat,const float*inv,const float*gamma,const float*dgamma,const float*dbeta,unsigned active,unsigned cap,unsigned global_rows,unsigned logical,unsigned physical,__nv_bfloat16*dz,float*residual){std::uint64_t q=(std::uint64_t)blockIdx.x*blockDim.x+threadIdx.x,n=(std::uint64_t)cap*physical;if(q>=n)return;unsigned row=q/physical,col=q-(std::uint64_t)row*physical;bool on=row<active&&col<logical&&((mask[(std::uint64_t)row*((physical+31)/32)+col/32]>>(col&31))&1U);float gated=on?up[q]:0.0f;if(residual)residual[q]=gated;float v=0;if(row<active&&col<logical){float nh=LoadXhat(xhat,q);v=gamma[col]*inv[col]/global_rows*(global_rows*gated-dbeta[col]-nh*dgamma[col]);}dz[q]=__float2bfloat16_rn(v);}
bool Valid(unsigned active,unsigned cap,unsigned logical,unsigned physical){return cap&&physical&&active<=cap&&logical<=physical;}
} // namespace
mgt::Status LaunchBf16BatchNormForwardEpilogue(const float*x,const float*mean,const float*inv,const float*gamma,const float*beta,const __nv_bfloat16*res,unsigned active,unsigned cap,unsigned logical,unsigned physical,mgt::A100XhatStorage storage,void*xhat,__nv_bfloat16*y,unsigned*mask,cudaStream_t stream){if(!x||!mean||!inv||!gamma||!beta||!xhat||!y||!mask||!Valid(active,cap,logical,physical))return mgt::Status::kInvalidConfig;dim3 grid(cap,(physical+31)/32);if(storage==mgt::A100XhatStorage::kFp32)Forward<<<grid,32,0,stream>>>(x,mean,inv,gamma,beta,res,active,cap,logical,physical,(float*)xhat,y,mask);else if(storage==mgt::A100XhatStorage::kBf16)Forward<<<grid,32,0,stream>>>(x,mean,inv,gamma,beta,res,active,cap,logical,physical,(__nv_bfloat16*)xhat,y,mask);else return mgt::Status::kInvalidConfig;return cudaPeekAtLastError()==cudaSuccess?mgt::Status::kOk:mgt::Status::kCudaFailure;}
mgt::Status LaunchBf16BatchNormBackwardEpilogue(const float*up,const unsigned*mask,const void*xhat,const float*inv,const float*gamma,const float*dgamma,const float*dbeta,unsigned active,unsigned cap,unsigned global_rows,unsigned logical,unsigned physical,mgt::A100XhatStorage storage,__nv_bfloat16*dz,float*residual,cudaStream_t stream){if(!up||!mask||!xhat||!inv||!gamma||!dgamma||!dbeta||!dz||!global_rows||global_rows<active||!Valid(active,cap,logical,physical))return mgt::Status::kInvalidConfig;std::uint64_t count=(std::uint64_t)cap*physical,blocks=(count+255)/256;if(blocks>std::numeric_limits<unsigned>::max())return mgt::Status::kCapacityExceeded;if(storage==mgt::A100XhatStorage::kFp32)Backward<<<(unsigned)blocks,256,0,stream>>>(up,mask,(const float*)xhat,inv,gamma,dgamma,dbeta,active,cap,global_rows,logical,physical,dz,residual);else if(storage==mgt::A100XhatStorage::kBf16)Backward<<<(unsigned)blocks,256,0,stream>>>(up,mask,(const __nv_bfloat16*)xhat,inv,gamma,dgamma,dbeta,active,cap,global_rows,logical,physical,dz,residual);else return mgt::Status::kInvalidConfig;return cudaPeekAtLastError()==cudaSuccess?mgt::Status::kOk:mgt::Status::kCudaFailure;}
} // namespace mgt_cuda
