#include "mgt_cuda/bf16_batch_norm_sites.cuh"
#include "mgt_cuda/bf16_batch_norm_epilogue.cuh"
#include "mgt_cuda/sync_batch_norm_tiled.cuh"
#include <limits>
namespace mgt_cuda { namespace {
bool Add(std::uint64_t a,std::uint64_t b,std::uint64_t*o){if(a>~std::uint64_t{0}-b)return false;*o=a+b;return true;}
bool Mul(std::uint64_t a,std::uint64_t b,std::uint64_t*o){if(a&&b>~std::uint64_t{0}/a)return false;*o=a*b;return true;}
const mgt::A100ArenaSliceV1* Find(const A100StaticArenaView&v,mgt::A100ArenaSliceKind k){if(!v.plan)return nullptr;for(std::uint32_t i=0;i<v.plan->slice_count;++i)if(v.plan->slices[i].kind==k)return &v.plan->slices[i];return nullptr;}
} // namespace
mgt::Status BuildBf16BatchNormSitesPlan(const CudaMlpShape&s,unsigned lh1,unsigned lh2,unsigned rows,unsigned slots,mgt::A100XhatStorage storage,Bf16BatchNormSitesPlan*out){if(!out||ValidateCudaMlpShape(s)!=mgt::Status::kOk||!lh1||!lh2||lh1>s.hd1||lh2>s.hd2||!rows||slots<2||slots>4||(storage!=mgt::A100XhatStorage::kFp32&&storage!=mgt::A100XhatStorage::kBf16))return mgt::Status::kInvalidConfig;std::uint64_t count64=2ULL+2ULL*s.residual_blocks;if(count64>kMaxBf16BatchNormSites)return mgt::Status::kCapacityExceeded;*out={};out->site_count=(unsigned)count64;out->capacity_rows=rows;out->dz_ring_slots=slots;out->max_physical_features=s.hd1>s.hd2?s.hd1:s.hd2;out->xhat_element_bytes=storage==mgt::A100XhatStorage::kFp32?4:2;std::uint64_t ae=0,xb=0,mb=0;for(unsigned i=0;i<out->site_count;++i){unsigned physical=i?s.hd2:s.hd1,logical=i?lh2:lh1;std::uint64_t elements,mask;if(!Mul(rows,physical,&elements)||!Mul(rows,(physical+31ULL)/32*4,&mask))return mgt::Status::kCapacityExceeded;auto&v=out->sites[i];v={i,logical,physical,ae,xb,mb,mask};std::uint64_t xbytes;if(!Mul(elements,out->xhat_element_bytes,&xbytes)||!Add(ae,elements,&ae)||!Add(xb,xbytes,&xb)||!Add(mb,mask,&mb))return mgt::Status::kCapacityExceeded;}return mgt::Status::kOk;}
mgt::Status QueryA100Bf16RuntimeBatchNormSite(A100Bf16Runtime*r,unsigned site,unsigned slot,Bf16BatchNormSiteView*out){if(!r||!out)return mgt::Status::kInvalidConfig;A100StaticArenaView v{};if(QueryA100Bf16RuntimeView(r,&v)!=mgt::Status::kOk)return mgt::Status::kInvalidConfig;const auto*p=A100Bf16RuntimeBatchNormSitesPlan(r);if(!p||site>=p->site_count||slot>=p->dz_ring_slots)return mgt::Status::kInvalidConfig;const auto*a=Find(v,mgt::A100ArenaSliceKind::kActivationsBf16),*x=Find(v,mgt::A100ArenaSliceKind::kXhat),*m=Find(v,mgt::A100ArenaSliceKind::kReluMasks),*d=Find(v,mgt::A100ArenaSliceKind::kDzRingBf16);if(!a||!x||!m||!d)return mgt::Status::kInvalidConfig;const auto&l=p->sites[site];std::uint64_t ae=l.activation_element_offset*2,xe=l.xhat_byte_offset,de=(std::uint64_t)slot*p->capacity_rows*p->max_physical_features*2;if(ae+(std::uint64_t)p->capacity_rows*l.physical_features*2>a->bytes||xe+(std::uint64_t)p->capacity_rows*l.physical_features*p->xhat_element_bytes>x->bytes||l.mask_byte_offset+l.mask_bytes>m->bytes||de+(std::uint64_t)p->capacity_rows*p->max_physical_features*2>d->bytes)return mgt::Status::kInvalidConfig;auto*base=(std::uint8_t*)v.ordinary_base;*out={&l,(__nv_bfloat16*)(base+a->offset+ae),(void*)(base+x->offset+xe),(std::uint32_t*)(base+m->offset+l.mask_byte_offset),(__nv_bfloat16*)(base+d->offset+de)};return mgt::Status::kOk;}
} // namespace mgt_cuda
mgt::Status mgt_cuda::LaunchA100Bf16BatchNormForwardSite(A100Bf16Runtime*r,std::uint32_t site,const float*pre,const float*mean,const float*inv,const float*gamma,const float*beta,const __nv_bfloat16*res,std::uint32_t rows){Bf16BatchNormSiteView v{};auto z=QueryA100Bf16RuntimeBatchNormSite(r,site,0,&v);if(z!=mgt::Status::kOk)return z;const auto*p=A100Bf16RuntimeBatchNormSitesPlan(r);auto storage=p->xhat_element_bytes==4?mgt::A100XhatStorage::kFp32:mgt::A100XhatStorage::kBf16;return LaunchBf16BatchNormForwardEpilogue(pre,mean,inv,gamma,beta,res,rows,p->capacity_rows,v.layout->logical_features,v.layout->physical_features,storage,v.xhat,v.activation,v.relu_mask,A100Bf16RuntimeComputeStream(r));}
mgt::Status mgt_cuda::LaunchA100Bf16BatchNormBackwardSite(A100Bf16Runtime*r,std::uint32_t site,std::uint32_t slot,const float*up,const float*inv,const float*gamma,const float*dg,const float*db,std::uint32_t rows,std::uint32_t global,float*residual){Bf16BatchNormSiteView v{};auto z=QueryA100Bf16RuntimeBatchNormSite(r,site,slot,&v);if(z!=mgt::Status::kOk)return z;const auto*p=A100Bf16RuntimeBatchNormSitesPlan(r);auto storage=p->xhat_element_bytes==4?mgt::A100XhatStorage::kFp32:mgt::A100XhatStorage::kBf16;return LaunchBf16BatchNormBackwardEpilogue(up,v.relu_mask,v.xhat,inv,gamma,dg,db,rows,p->capacity_rows,global,v.layout->logical_features,v.layout->physical_features,storage,v.dz,residual,A100Bf16RuntimeComputeStream(r));}
mgt::Status mgt_cuda::LaunchA100TiledSyncBatchNormForwardSite(A100Bf16Runtime*r,std::uint32_t site,const float*pre,const __nv_bfloat16*res,std::uint32_t rows,std::uint32_t global,const float*gamma,const float*beta,float*running_mean,float*running_variance,float momentum,float epsilon,float*mean,float*inv){Bf16BatchNormSiteView v{};auto z=QueryA100Bf16RuntimeBatchNormSite(r,site,0,&v);if(z!=mgt::Status::kOk)return z;const auto*c=A100Bf16RuntimeBatchNormConfig(r);const auto*w=A100Bf16RuntimeBatchNormWorkspace(r);auto*ctx=A100Bf16RuntimeBatchNormContext(r);if(!c||!w||!ctx)return mgt::Status::kInvalidConfig;return LaunchTiledSyncBatchNormForward(*c,pre,res,rows,w->partial_count?A100Bf16RuntimeBatchNormSitesPlan(r)->capacity_rows:0,global,v.layout->logical_features,v.layout->physical_features,gamma,beta,running_mean,running_variance,momentum,epsilon,mean,inv,v.xhat,v.activation,v.relu_mask,*w,ctx,A100Bf16RuntimeComputeStream(r));}
mgt::Status mgt_cuda::LaunchA100TiledSyncBatchNormBackwardSite(A100Bf16Runtime*r,std::uint32_t site,std::uint32_t slot,const float*up,const float*inv,const float*gamma,float*dg,float*db,std::uint32_t rows,std::uint32_t global,float*residual){Bf16BatchNormSiteView v{};auto z=QueryA100Bf16RuntimeBatchNormSite(r,site,slot,&v);if(z!=mgt::Status::kOk)return z;const auto*c=A100Bf16RuntimeBatchNormConfig(r);const auto*w=A100Bf16RuntimeBatchNormWorkspace(r);auto*ctx=A100Bf16RuntimeBatchNormContext(r);if(!c||!w||!ctx)return mgt::Status::kInvalidConfig;return LaunchTiledSyncBatchNormBackward(*c,up,v.relu_mask,v.xhat,rows,A100Bf16RuntimeBatchNormSitesPlan(r)->capacity_rows,global,v.layout->logical_features,v.layout->physical_features,gamma,inv,dg,db,v.dz,residual,*w,ctx,A100Bf16RuntimeComputeStream(r));}
