#include "mgt_cuda/mlp_batch_norm_forward.cuh"
#include "batch_norm_activation.cuh"
#include "sync_batch_norm.cuh"
#include <algorithm>
namespace mgt_cuda { namespace {
constexpr unsigned T=256;
__host__ __device__ std::uint64_t RB(CudaMlpShape s){return 2ULL*(static_cast<std::uint64_t>(s.hd2)*s.hd2+s.hd2);}__host__ __device__ std::uint64_t IB(CudaMlpShape s){return static_cast<std::uint64_t>(s.state_len)*s.state_value_pad*s.hd1;}__host__ __device__ std::uint64_t HW(CudaMlpShape s){return IB(s)+s.hd1;}__host__ __device__ std::uint64_t HB(CudaMlpShape s){return HW(s)+static_cast<std::uint64_t>(s.hd1)*s.hd2;}__host__ __device__ std::uint64_t R0(CudaMlpShape s){return HB(s)+s.hd2;}__host__ __device__ std::uint64_t OW(CudaMlpShape s){return R0(s)+static_cast<std::uint64_t>(s.residual_blocks)*RB(s);}__host__ __device__ std::uint64_t OB(CudaMlpShape s){return OW(s)+static_cast<std::uint64_t>(s.hd2)*s.output_dim;}__host__ __device__ std::uint64_t F1W(CudaMlpShape s,unsigned b){return R0(s)+static_cast<std::uint64_t>(b)*RB(s);}__host__ __device__ std::uint64_t F1B(CudaMlpShape s,unsigned b){return F1W(s,b)+static_cast<std::uint64_t>(s.hd2)*s.hd2;}__host__ __device__ std::uint64_t F2W(CudaMlpShape s,unsigned b){return F1B(s,b)+s.hd2;}__host__ __device__ std::uint64_t F2B(CudaMlpShape s,unsigned b){return F2W(s,b)+static_cast<std::uint64_t>(s.hd2)*s.hd2;}
__global__ void Input(CudaMlpShape s,unsigned logical,const float*w,const mgt::TrainStateStorage*states,unsigned rows,float*out){unsigned q=blockIdx.x*blockDim.x+threadIdx.x;if(q>=rows*s.hd1)return;unsigned r=q/s.hd1,h=q-r*s.hd1;if(h>=logical){out[q]=0;return;}float v=w[IB(s)+h];for(unsigned p=0;p<s.state_len;p++)v+=w[(static_cast<std::uint64_t>(p)*s.state_value_pad+states[r].v[p])*s.hd1+h];out[q]=v;}
__global__ void Bias(float*x,const float*b,unsigned rows,unsigned stride,unsigned logical){unsigned q=blockIdx.x*blockDim.x+threadIdx.x;if(q>=rows*stride)return;unsigned c=q%stride;x[q]=c<logical?x[q]+b[c]:0;}
__global__ void OutputBias(float*x,const float*b,unsigned rows,unsigned cols){unsigned q=blockIdx.x*blockDim.x+threadIdx.x;if(q<rows*cols)x[q]+=b[q%cols];}
mgt::Status Gemm(cublasHandle_t h,const float*a,const float*b,float*c,unsigned m,unsigned n,unsigned k){float alpha=1,beta=0;return cublasSgemm(h,CUBLAS_OP_N,CUBLAS_OP_N,n,m,k,&alpha,b,n,a,k,&beta,c,n)==CUBLAS_STATUS_SUCCESS?mgt::Status::kOk:mgt::Status::kCudaFailure;}
bool launch(){return cudaPeekAtLastError()==cudaSuccess;}
}
std::uint64_t MlpBatchNormForwardWorkspaceFloats(const CudaMlpShape&s,const mgt::BatchNormTrainingPlan&p,std::uint32_t rows){if(!rows||p.workspace_floats==0)return 0;return static_cast<std::uint64_t>(rows)*(s.hd1+3ULL*s.hd2)+p.workspace_floats;}
mgt::Status LaunchMlpBatchNormForward(const CudaMlpShape&s,std::uint32_t lh1,std::uint32_t lh2,const float*w,float*aff,float*run,const mgt::TrainStateStorage*states,std::uint32_t lr,std::uint32_t gr,float*out,float*base,std::uint64_t count,const mgt::BatchNormTrainingPlan&p,NcclRankContext*ctx,cublasHandle_t blas,cudaStream_t st){if(ValidateCudaMlpShape(s)!=mgt::Status::kOk||!lh1||!lh2||lh1>s.hd1||lh2>s.hd2||!w||!aff||!run||!states||!lr||gr<lr||!out||!base||!ctx||!blas||p.sites.size()!=2+2*s.residual_blocks||count<MlpBatchNormForwardWorkspaceFloats(s,p,lr))return mgt::Status::kInvalidConfig;if(cublasSetStream(blas,st)!=CUBLAS_STATUS_SUCCESS)return mgt::Status::kCudaFailure;float*a1=base;base+=static_cast<std::uint64_t>(lr)*s.hd1;float*cur=base;base+=static_cast<std::uint64_t>(lr)*s.hd2;float*f1=base;base+=static_cast<std::uint64_t>(lr)*s.hd2;float*f2=base;base+=static_cast<std::uint64_t>(lr)*s.hd2;float*bn=base;float*scratch=bn+p.reduction_offset;auto site=[&](unsigned i,float*x){const auto&q=p.sites[i];return LaunchStridedSyncBatchNormForward(x,lr,gr,q.logical_features,q.physical_stride,aff+q.affine_offset,aff+p.logical_feature_count+q.affine_offset,run+q.running_offset,run+p.logical_feature_count+q.running_offset,.1f,1e-5f,x,bn+q.mean_offset,bn+q.inv_std_offset,bn+q.normalized_offset,scratch,ctx,st);};unsigned blocks1=(lr*s.hd1+T-1)/T,blocks2=(lr*s.hd2+T-1)/T;Input<<<blocks1,T,0,st>>>(s,lh1,w,states,lr,a1);if(!launch()||site(0,a1)!=mgt::Status::kOk||LaunchBatchNormReluForward(a1,static_cast<std::uint64_t>(lr)*s.hd1,st)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;if(Gemm(blas,a1,w+HW(s),cur,lr,s.hd2,s.hd1)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;Bias<<<blocks2,T,0,st>>>(cur,w+HB(s),lr,s.hd2,lh2);if(!launch()||site(1,cur)!=mgt::Status::kOk||LaunchBatchNormReluForward(cur,static_cast<std::uint64_t>(lr)*s.hd2,st)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;for(unsigned b=0;b<s.residual_blocks;b++){if(Gemm(blas,cur,w+F1W(s,b),f1,lr,s.hd2,s.hd2)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;Bias<<<blocks2,T,0,st>>>(f1,w+F1B(s,b),lr,s.hd2,lh2);if(!launch()||site(2+2*b,f1)!=mgt::Status::kOk||LaunchBatchNormReluForward(f1,static_cast<std::uint64_t>(lr)*s.hd2,st)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;if(Gemm(blas,f1,w+F2W(s,b),f2,lr,s.hd2,s.hd2)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;Bias<<<blocks2,T,0,st>>>(f2,w+F2B(s,b),lr,s.hd2,lh2);if(!launch()||site(3+2*b,f2)!=mgt::Status::kOk||LaunchBatchNormResidualReluForward(cur,f2,static_cast<std::uint64_t>(lr)*s.hd2,st)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;std::swap(cur,f2);}if(Gemm(blas,cur,w+OW(s),out,lr,s.output_dim,s.hd2)!=mgt::Status::kOk)return mgt::Status::kCudaFailure;unsigned bo=(lr*s.output_dim+T-1)/T;OutputBias<<<bo,T,0,st>>>(out,w+OB(s),lr,s.output_dim);return launch()?mgt::Status::kOk:mgt::Status::kCudaFailure;}
}