#include "sync_batch_norm.cuh"
namespace mgt_cuda { namespace {
constexpr int T=256;
__global__ void LocalMoments(const float* x,int rows,int cols,float* w){int c=blockIdx.x; __shared__ float s[T],q[T]; float a=0,b=0; for(int r=threadIdx.x;r<rows;r+=T){float v=x[r*cols+c];a+=v;b+=v*v;} s[threadIdx.x]=a;q[threadIdx.x]=b;__syncthreads();for(int d=T/2;d;d>>=1){if(threadIdx.x<d){s[threadIdx.x]+=s[threadIdx.x+d];q[threadIdx.x]+=q[threadIdx.x+d];}__syncthreads();}if(!threadIdx.x){w[c]=s[0];w[cols+c]=q[0];}}
__global__ void FinalMoments(const float* w,int n,int cols,float mom,float eps,float* rm,float* rv,float* mean,float* inv){int c=blockIdx.x*T+threadIdx.x;if(c<cols){float m=w[c]/n;float v=fmaxf(w[cols+c]/n-m*m,0.f);mean[c]=m;inv[c]=rsqrtf(v+eps);rm[c]=(1-mom)*rm[c]+mom*m;float u=n>1?v*n/(n-1):0;rv[c]=(1-mom)*rv[c]+mom*u;}}
__global__ void Norm(const float*x,int count,int cols,const float*g,const float*b,const float*m,const float*inv,float*y,float*xh){int i=blockIdx.x*T+threadIdx.x;if(i<count){int c=i%cols;float z=(x[i]-m[c])*inv[c];xh[i]=z;y[i]=z*g[c]+b[c];}}
__global__ void LocalGrads(const float*dy,const float*xh,int rows,int cols,float*w){int c=blockIdx.x;__shared__ float a[T],b[T];float ga=0,be=0;for(int r=threadIdx.x;r<rows;r+=T){int i=r*cols+c;be+=dy[i];ga+=dy[i]*xh[i];}a[threadIdx.x]=ga;b[threadIdx.x]=be;__syncthreads();for(int d=T/2;d;d>>=1){if(threadIdx.x<d){a[threadIdx.x]+=a[threadIdx.x+d];b[threadIdx.x]+=b[threadIdx.x+d];}__syncthreads();}if(!threadIdx.x){w[c]=a[0];w[cols+c]=b[0];}}
__global__ void CopyGrads(const float*w,int cols,float*dg,float*db){int c=blockIdx.x*T+threadIdx.x;if(c<cols){dg[c]=w[c];db[c]=w[cols+c];}}
__global__ void Dx(const float*dy,int count,int n,int cols,const float*g,const float*inv,const float*xh,const float*dg,const float*db,float*dx){int i=blockIdx.x*T+threadIdx.x;if(i<count){int c=i%cols;dx[i]=g[c]*inv[c]/n*(n*dy[i]-db[c]-xh[i]*dg[c]);}}
bool valid(const float*p,int lr,int gr,int c,ncclComm_t comm){return p&&lr>0&&gr>=lr&&c>0&&comm;}
}
mgt::Status LaunchSyncBatchNormForward(const float*x,int lr,int gr,int c,const float*g,const float*b,float*rm,float*rv,float mom,float eps,float*y,float*mean,float*inv,float*xh,float*w,ncclComm_t comm,cudaStream_t st){if(!valid(x,lr,gr,c,comm)||!g||!b||!rm||!rv||!y||!mean||!inv||!xh||!w||eps<=0)return mgt::Status::kInvalidConfig;LocalMoments<<<c,T,0,st>>>(x,lr,c,w);if(ncclAllReduce(w,w,2*c,ncclFloat32,ncclSum,comm,st)!=ncclSuccess)return mgt::Status::kNcclFailure;FinalMoments<<<(c+T-1)/T,T,0,st>>>(w,gr,c,mom,eps,rm,rv,mean,inv);Norm<<<(lr*c+T-1)/T,T,0,st>>>(x,lr*c,c,g,b,mean,inv,y,xh);return cudaPeekAtLastError()==cudaSuccess?mgt::Status::kOk:mgt::Status::kCudaFailure;}
mgt::Status LaunchSyncBatchNormBackward(const float*dy,int lr,int gr,int c,const float*g,const float*inv,const float*xh,float*dx,float*dg,float*db,float*w,ncclComm_t comm,cudaStream_t st){if(!valid(dy,lr,gr,c,comm)||!g||!inv||!xh||!dx||!dg||!db||!w)return mgt::Status::kInvalidConfig;LocalGrads<<<c,T,0,st>>>(dy,xh,lr,c,w);if(ncclAllReduce(w,w,2*c,ncclFloat32,ncclSum,comm,st)!=ncclSuccess)return mgt::Status::kNcclFailure;CopyGrads<<<(c+T-1)/T,T,0,st>>>(w,c,dg,db);Dx<<<(lr*c+T-1)/T,T,0,st>>>(dy,lr*c,gr,c,g,inv,xh,dg,db,dx);return cudaPeekAtLastError()==cudaSuccess?mgt::Status::kOk:mgt::Status::kCudaFailure;}
}