#include "sync_batch_norm.cuh"
#include "mgt/batch_norm.hpp"
#include <cuda_runtime.h>
#include <nccl.h>
#include <cmath>
#include <cstdlib>
#include <thread>
#include <vector>
struct B{float*x,*dy,*g,*b,*rm,*rv,*y,*mean,*inv,*xh,*dx,*dg,*db,*w;cudaStream_t s;};
bool near(float a,float b){return std::fabs(a-b)<2e-4f;}
int main(){int ndev=0;cudaGetDeviceCount(&ndev);if(ndev<2)return 0;constexpr int R=2,N=2,C=2;int dev[R]={0,1};ncclComm_t comm[R];if(ncclCommInitAll(comm,R,dev)!=ncclSuccess)return 1;float hx[R][N*C]={{0,2,1,3},{10,14,12,16}};float hdy[R][N*C]={{1,-1,2,.5f},{-.5f,1.5f,.25f,-2}};float hg[C]={1.2f,.7f},hb[C]={.1f,-.2f};B z[R]{};for(int r=0;r<R;r++){cudaSetDevice(r);cudaStreamCreate(&z[r].s);float**p[]={&z[r].x,&z[r].dy,&z[r].y,&z[r].xh,&z[r].dx};for(auto q:p)cudaMalloc(q,N*C*sizeof(float));float**v[]={&z[r].g,&z[r].b,&z[r].rm,&z[r].rv,&z[r].mean,&z[r].inv,&z[r].dg,&z[r].db,&z[r].w};for(auto q:v)cudaMalloc(q,2*C*sizeof(float));cudaMemcpy(z[r].x,hx[r],N*C*4,cudaMemcpyHostToDevice);cudaMemcpy(z[r].dy,hdy[r],N*C*4,cudaMemcpyHostToDevice);cudaMemcpy(z[r].g,hg,C*4,cudaMemcpyHostToDevice);cudaMemcpy(z[r].b,hb,C*4,cudaMemcpyHostToDevice);cudaMemset(z[r].rm,0,C*4);std::vector<float> one(C,1);cudaMemcpy(z[r].rv,one.data(),C*4,cudaMemcpyHostToDevice);}
int ok[R]={};std::thread th[R];for(int r=0;r<R;r++)th[r]=std::thread([&,r]{cudaSetDevice(r);auto a=mgt_cuda::LaunchSyncBatchNormForward(z[r].x,N,R*N,C,z[r].g,z[r].b,z[r].rm,z[r].rv,.1f,1e-5f,z[r].y,z[r].mean,z[r].inv,z[r].xh,z[r].w,comm[r],z[r].s);auto b=mgt_cuda::LaunchSyncBatchNormBackward(z[r].dy,N,R*N,C,z[r].g,z[r].inv,z[r].xh,z[r].dx,z[r].dg,z[r].db,z[r].w,comm[r],z[r].s);ok[r]=(a==mgt::Status::kOk&&b==mgt::Status::kOk&&cudaStreamSynchronize(z[r].s)==cudaSuccess);});for(auto&t:th)t.join();if(!ok[0]||!ok[1])return 1;
float allx[R*N*C],alldy[R*N*C];for(int r=0;r<R;r++)for(int i=0;i<N*C;i++){allx[r*N*C+i]=hx[r][i];alldy[r*N*C+i]=hdy[r][i];}float rm[C]={},rv[C]={1,1},cy[R*N*C],cdx[R*N*C],cdg[C],cdb[C];mgt::BatchNormCache cache;mgt::batch_norm_forward_cpu(allx,R*N,C,hg,hb,rm,rv,.1f,1e-5f,true,cy,&cache);mgt::batch_norm_backward_cpu(alldy,cache,hg,cdx,cdg,cdb);for(int r=0;r<R;r++){float y[N*C],dx[N*C],dg[C],db[C];cudaSetDevice(r);cudaMemcpy(y,z[r].y,N*C*4,cudaMemcpyDeviceToHost);cudaMemcpy(dx,z[r].dx,N*C*4,cudaMemcpyDeviceToHost);cudaMemcpy(dg,z[r].dg,C*4,cudaMemcpyDeviceToHost);cudaMemcpy(db,z[r].db,C*4,cudaMemcpyDeviceToHost);for(int i=0;i<N*C;i++)if(!near(y[i],cy[r*N*C+i])||!near(dx[i],cdx[r*N*C+i]))return 1;for(int c=0;c<C;c++)if(!near(dg[c],cdg[c])||!near(db[c],cdb[c]))return 1;}return 0;}